import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  apiPlugin,
  StoryblokBridgeLoader,
  storyblokInit,
} from "@storyblok/react/rsc";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken: process.env.STORYBLOK_ACCESS_TOKEN,
  use: [apiPlugin],
  components: {},
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bridgeOptions = { resolveRelations: ["article.author"] };

  return (
    <html lang="en">
      <body className={inter.className}>
        <main>{children}</main>
      </body>
      <StoryblokBridgeLoader options={bridgeOptions} />
    </html>
  );
}
